[profile.default]
solc_version = "0.8.26"
evm_version = "cancun"

optimizer = true
optimizer_runs = 9_999_999

via_ir = true

remappings = [
  "@v4=lib/v4-core/",
  "v4-periphery=lib/v4-periphery/contracts/",
  "@solady=lib/solady/",
  "@forge=lib/forge-std/src/"
]


[fmt]
line_length = 100

[rpc_endpoints]
main = "https://rpc.ankr.com/eth"
base = "https://rpc.ankr.com/base"
poly = "https://rpc.ankr.com/polygon"
opti = "https://rpc.ankr.com/optimism"
arbi = "https://rpc.ankr.com/arbitrum"